spring.application.name=cat

# Cloud Run provides the container port via the PORT env var.
server.port=${PORT:8080}

# Better SIGTERM handling on Cloud Run.
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Set to the Postgres user you want to connect to; 'postgres' is the default user.
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PWD}
spring.cloud.gcp.sql.database-name=postgres
spring.cloud.gcp.sql.instance-connection-name=project-1645ae7c-181a-4b21-9cd:europe-west1:postgres-cats
# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.sql.init.mode=always

#pubsub config
pubsub.topic=testTopic
pubsub.subscription=testTopic-sub

# Actuator Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

auth.token.api=https://dev-xjtz6ps1llg7ich0.us.auth0.com/oauth/token
auth.client-id:70jBOJCZ9M0wqa1DjwuSbeSIgFMKOSia
auth.client-secret:fh8Vo2UjA0WMLn-n2TLRtUDe-45b12I2QMHJMn-GOlobRb19SXRc_eb22eaE4h_f